# Generated by Django 2.2.6 on 2019-12-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='full_marks',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='problems',
            field=models.ManyToManyField(default=None, to='challenges.Challenges'),
        ),
    ]
