# Generated by Django 2.2.6 on 2019-12-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20191211_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='full_marks',
            field=models.IntegerField(default=0),
        ),
    ]
