# Generated by Django 2.2.6 on 2019-12-11 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20191211_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 11, 42, 33, 6511)),
        ),
    ]
