# Generated by Django 2.2.6 on 2019-10-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='31class', max_length=20, unique=True)),
                ('team_number', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['team_name'],
            },
        ),
    ]
