# Generated by Django 2.2.6 on 2019-10-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20191012_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
