# Generated by Django 2.2.6 on 2019-10-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseName', models.CharField(max_length=10, unique=True)),
                ('baseId', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
