# Generated by Django 2.2.6 on 2019-10-20 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_student_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.RemoveField(
            model_name='team',
            name='player_number',
        ),
        migrations.AddField(
            model_name='team',
            name='team_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_name',
            field=models.CharField(default='31class', max_length=20, unique=True),
        ),
    ]
