# Generated by Django 2.2.6 on 2019-10-21 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191020_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_leader',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='accounts.User'),
        ),
    ]
