# Generated by Django 2.2.6 on 2019-10-21 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_team_team_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_leader',
        ),
    ]
