# Generated by Django 2.2.6 on 2019-10-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_team_team_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_leader',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
