# Generated by Django 2.2.6 on 2019-10-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['point'], 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
    ]
