# Generated by Django 2.2.6 on 2019-10-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191028_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-point'], 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
        migrations.AddField(
            model_name='team',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
