# Generated by Django 2.2.6 on 2019-11-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20191102_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='1111@123.com', max_length=254, unique=True),
        ),
    ]
