# Generated by Django 2.2.6 on 2019-11-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20191102_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmstring',
            options={'ordering': ['-c_time'], 'verbose_name': 'confirm_code', 'verbose_name_plural': 'confirm_code'},
        ),
    ]
