# Generated by Django 2.2.6 on 2019-12-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggestion',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
