# Generated by Django 2.2.6 on 2019-10-26 10:06

import challenges.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=10)),
                ('massage', models.CharField(blank=True, default='', max_length=1000)),
                ('point', models.IntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to=challenges.models.get_upload_path)),
                ('flag', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'challenge',
                'verbose_name_plural': 'challenges',
            },
        ),
    ]
