# Generated by Django 2.2.6 on 2019-10-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='solver',
            field=models.ManyToManyField(to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='category',
            field=models.IntegerField(choices=[('0', 'RE'), ('1', 'WEB'), ('2', 'PWN')]),
        ),
    ]
