# Generated by Django 2.2.6 on 2019-10-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenges',
            options={'verbose_name': 'challenge', 'verbose_name_plural': 'challenges'},
        ),
        migrations.AlterModelOptions(
            name='challengessolvedby',
            options={'verbose_name': 'solvedChallenge'},
        ),
    ]
