# Generated by Django 2.2.6 on 2019-10-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_auto_20191026_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='category',
            field=models.IntegerField(choices=[(0, 'RE'), (1, 'WEB'), (2, 'PWN')]),
        ),
    ]
