# Generated by Django 2.2.6 on 2019-10-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_auto_20191027_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='solver',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='accounts.User'),
        ),
    ]
