# Generated by Django 2.2.6 on 2019-10-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_auto_20191027_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='solver',
            field=models.ManyToManyField(blank=True, default=None, to='accounts.User'),
        ),
    ]
