# Generated by Django 2.2.6 on 2019-10-29 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_auto_20191028_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='massage',
            new_name='message',
        ),
    ]
