# Generated by Django 2.2.6 on 2019-12-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20191207_2105'),
        ('challenges', '0008_challenges_scene'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='collector',
            field=models.ManyToManyField(blank=True, default=None, related_name='collect', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='challenges',
            name='solver',
            field=models.ManyToManyField(blank=True, default=None, related_name='solve', to='accounts.User'),
        ),
    ]
