# Generated by Django 2.2.6 on 2019-12-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_auto_20191209_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='category',
            field=models.IntegerField(choices=[(0, 'RE'), (1, 'WEB'), (2, 'PWN'), (3, 'CRYPTO')]),
        ),
    ]
