# Generated by Django 2.2.6 on 2019-12-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_auto_20191210_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='scene',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
